Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/data/srlab2/jmears/jupyter/SLE_Phase2_Kidney_Analysis/cell-seq-output/full_metadata/meta_filtered_all_500nGene_1000nUMI_3pctnontargetMTwdoubletandsample.rds', probable reason 'No such file or directory'
Execution halted
Error in `$<-.data.frame`(`*tmp*`, uwotUMAP1, value = c(-4.23138065849174,  : 
  replacement has 653556 rows, data has 669096
Calls: $<- -> $<-.data.frame
Execution halted
